### PR TITLE
remove write-stream

### PR DESCRIPTION
**Pull request by ralphtheninja**

### CODE REVIEW

**Comment by mcollina** [comment]
LGTM

**Comment by hij1nx** [comment]
I'm sure that @rvagg is gonna be hurt that `boganipsum` is gone, but otherwise it looks fine. What are we going to do for documentation? (probably better to address with another commit)

**Comment by hij1nx** [comment]
Oh, I guess I missed the message that was added which says it's been removed.

**Comment by ralphtheninja** [comment]
I can put back `boganipsum` for sentimental reasons, if needed ;)

**Comment by jcrugzz** [comment]
@ralphtheninja LGTM. Good work :+1:

**Comment by ralphtheninja** [comment]
@jcrugzz All the work was already made. Just placing the ball on the penalty point so hopefully @rvagg can kick in the ball next week ;)

**Comment by juliangruber** [comment]
+1! great work @ralphtheninja!

**Pull request merged**
