### PR TITLE
1.0.0-wip

### PR DESCRIPTION
**Pull request by kesla**
Let's get a 1.0.0 done to compliment leveldown@1.0.0

- [x] Update leveldown to 1.0.0
- [x] Allow saving of empty values
- [x] Remove write-stream (#207)

Have I missed something else we should try and get into this release?

### CODE REVIEW

**Comment by ralphtheninja** [comment]
Ok, so now four more months has passed. Lets give this a try again :)

I think we all want to get `1.0.0` out the door. If I understood this correctly, the question is rather if we want to keep write stream or not.

Releasing `1.0.0` imo has higher priority than throwing out the write stream and is a decision we could push into the future.

Once `1.0.0` is out, we can decide to deprecate the write stream and release `1.1.0` and then release `2.0.0` without the write stream but with tests showing a canonical example.

**Comment by juliangruber** [comment]
what if we really just leave the simplest api compatible version of a writeStream in core, so it still works but people who require faster performance are advised to use another module.

something like this:

```js
db.prototype.createWriteStream = function(){
  var self = this;
  var w = Writable();
  w._write = function(kv, _, done){
    var method = kv.type || 'put';
    db.put(kv.key, kv.value, done);
  }
}
```

**Comment by ralphtheninja** [comment]
sgtm, we should probably do _something_ while we're releasing `1.0.0`

**Comment by jcrugzz** [comment]
Yea having removed it I have no qualms with postponing that removal if people are still back and forth on it. Versions are cheap, I'm +1 for shipping `1.0.0`

**Comment by mcollina** [comment]
Let's ship 1.0.0. But we need to change the writestream implementation anyway here (something like https://github.com/rvagg/node-levelup/pull/177), or we just add a very noisy deprecation flag and ship the current code.

**Comment by jcrugzz** [comment]
@mcollina i say we go with dropping in [`level-ws`](https://github.com/Level/level-ws) as a dep or do something super simple like what @juliangruber proposed as we should discourage and give examples for other write-stream implementations. The old `write-stream` implementation lives in [`level-fstream`](https://github.com/Level/level-fstream)

**Comment by dominictarr** [comment]
my vote: delete the write stream tests, and delete write stream.
link to write stream modules. done.

**Comment by mcollina** [comment]
This is not bad at all. Let's rely on the community for the integration
tests, this module is stable and the API is 'done', when we remove
writestream.
Il giorno mar 10 mar 2015 alle 09:03 Dominic Tarr <notifications@github.com>
ha scritto:

**Comment by ralphtheninja** [comment]
I'm with @dominictarr on this

**Comment by juliangruber** [comment]
ok yeah, I agree as well!

**Comment by ralphtheninja** [comment]
I propose the following procedure:

1. Merge https://github.com/Level/level-ws/pull/2
2. Release `1.0.0` of `level-ws`
3. Update https://github.com/rvagg/node-levelup/pull/296 to use `1.0.0` of `level-ws`
4. Merge https://github.com/rvagg/node-levelup/pull/296 into _this_ PR (ticking the last checkbox)
5. Rebase `1.0.0-wip` onto latest `master`
6. Release `1.0.0` of `levelup`

**Comment by mcollina** [comment]
:+1: for me.

**Comment by jcrugzz** [comment]
@ralphtheninja @mcollina functional tests live in `level-fstream` so id just rip them out. You can see if rebasing my branch is any easier.

**Comment by ralphtheninja** [comment]
@jcrugzz :+1: I'm rebasing your branch onto `1.0.0-wip` and pushing up to this repo for now. With your branch we don't have to wait for `level-ws` to be merged. So up to the community what we want. @rvagg 's branch with `level-ws` tests or @jcrugzz 's branch with no `level-ws` tests :)

**Comment by mcollina** [comment]
no level-ws tests for me, and leave ws to the community. We need a good
README explaining this removal, though.
Il giorno mar 10 mar 2015 alle 17:28 Lars-Magnus Skog <
notifications@github.com> ha scritto:

**Comment by ralphtheninja** [comment]
@jcrugzz Mind adding some some to this section?

https://github.com/rvagg/node-levelup/tree/remove-ws#what-happened-to-dbcreatewritestream

There are a few typos and a todo comment.

**Comment by rvagg** [comment]
fwiw I'm onsite with a client this week (and last) but plan on dedicating next week to some of my open source backlog and this is near the top of my list, unfortunately I can't afford the headspace to get stuck in here until then but you're welcome to hold me to getting to this next week!

**Comment by ralphtheninja** [comment]
@rvagg Hopefully you'll only need to publish when you come back :)

**Comment by ralphtheninja** [comment]
I merged `master` into `1.0.0-wip` so merging this PR should be trivial.

**Comment by jcrugzz** [comment]
Big +1 to this PR and @ralphtheninja !

**Comment by juliangruber** [comment]
I'm merging now since there's so many +1s and this project desparately needs a new version

**Comment by ralphtheninja** [comment]
:dancers:

**Comment by mcollina** [comment]
So :beers: for everybody. It's St. Patrick's day too!! :dancers:

**Comment by mcollina** [comment]
@rvagg it's your turn to publish this goodness, so we can all start updating our modules!

**Comment by kesla** [comment]
BOOM! :+1:

**Comment by mattstyles** [comment]
Not really the place to plaudits but... :beers: :clap:

**Pull request merged**
